const coffeeShops = [
    {
        id: 1,
        name: "WFM Coffee Bar",
        latitude: 40.8077971,
        longitude: -73.9459401,
        address: "100 W 125th St, New York",
        neighborhood: "East Harlem",
        rating: 3.0,
        reviews: 2,
        features: ["wifi","outdoor seating"]
    },
    {
        id: 2,
        name: "Bluestone Lane Upper East Side Café",
        latitude: 40.783823,
        longitude: -73.9585253,
        address: "1085 5th Ave, New York",
        neighborhood: "East Harlem",
        rating: 4.3,
        reviews: 1406,
        features: ["coffee","wifi","food","outdoor seating"]
    },
    {
        id: 3,
        name: "Sipsteria (Espresso & Natural Wine Bar)",
        latitude: 40.8110601,
        longitude: -73.9583998,
        address: "1264 Amsterdam Ave, New York",
        neighborhood: "East Harlem",
        rating: 4.7,
        reviews: 210,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 4,
        name: "Arbero",
        latitude: 40.7899134,
        longitude: -73.9524506,
        address: "1468 Madison Ave, New York",
        neighborhood: "East Harlem",
        rating: 5.0,
        reviews: 1,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 5,
        name: "The Townhouse Cafe",
        latitude: 40.7913342,
        longitude: -73.9467208,
        address: "1669 Lexington Ave Store, New York",
        neighborhood: "East Harlem",
        rating: 5.0,
        reviews: 98,
        features: ["coffee","wifi","food","outdoor seating"]
    },
    {
        id: 6,
        name: "Sunshine Cafe",
        latitude: 40.7807465,
        longitude: -73.9167592,
        address: "21-76 21st St, Astoria",
        neighborhood: "East Harlem",
        rating: 4.9,
        reviews: 438,
        features: ["coffee","wifi","food","outdoor seating"]
    },
    {
        id: 7,
        name: "Aroma Coffee Shop",
        latitude: 40.7929528,
        longitude: -73.9404833,
        address: "2132 2nd Ave, New York",
        neighborhood: "East Harlem",
        rating: 4.7,
        reviews: 39,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 8,
        name: "El Barrista cafe",
        latitude: 40.7991571,
        longitude: -73.9394953,
        address: "2154 3rd Ave #2, New York",
        neighborhood: "East Harlem",
        rating: 4.6,
        reviews: 406,
        features: ["coffee","wifi","food","outdoor seating"]
    },
    {
        id: 9,
        name: "Double Dutch Espresso",
        latitude: 40.8058777,
        longitude: -73.9540937,
        address: "2194 Frederick Douglass Blvd, New York",
        neighborhood: "East Harlem",
        rating: 4.5,
        reviews: 582,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 10,
        name: "Don Alejo Coffee",
        latitude: 40.7973086,
        longitude: -73.9389036,
        address: "228 E 116th St, New York",
        neighborhood: "East Harlem",
        rating: 4.8,
        reviews: 141,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 11,
        name: "Dell'Aria - Italian Love for Coffee",
        latitude: 40.7939874,
        longitude: -73.9411026,
        address: "232 E 111th St, New York",
        neighborhood: "East Harlem",
        rating: 4.7,
        reviews: 240,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 12,
        name: "9TAILS COFFEE SHOP",
        latitude: 40.8075271,
        longitude: -73.9432408,
        address: "34 W 126th St, New York",
        neighborhood: "East Harlem",
        rating: 4.7,
        reviews: 177,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 13,
        name: "Azalea Café",
        latitude: 40.7959117,
        longitude: -73.9347671,
        address: "409 E 116th St, New York",
        neighborhood: "East Harlem",
        rating: 4.7,
        reviews: 144,
        features: ["coffee","wifi","food","outdoor seating"]
    },
    {
        id: 14,
        name: "I Like It Black",
        latitude: 40.8117784,
        longitude: -73.9545007,
        address: "409 W 125th St, New York",
        neighborhood: "East Harlem",
        rating: 4.7,
        reviews: 227,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 15,
        name: "Everett Library Cafe",
        latitude: 40.8101745,
        longitude: -73.9606229,
        address: "525 W 120th St, New York",
        neighborhood: "East Harlem",
        rating: 4.7,
        reviews: 3,
        features: ["coffee","wifi","food","outdoor seating"]
    },
    {
        id: 16,
        name: "787 Coffee",
        latitude: 40.8100437,
        longitude: -73.9433169,
        address: "60 W 129th St, New York",
        neighborhood: "East Harlem",
        rating: 4.9,
        reviews: 1365,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 17,
        name: "Ginjan Cafe",
        latitude: 40.805319,
        longitude: -73.9392362,
        address: "85 E 125th St, New York",
        neighborhood: "East Harlem",
        rating: 4.9,
        reviews: 573,
        features: ["coffee","wifi","food","outdoor seating"]
    },
    {
        id: 18,
        name: "Nous Espresso",
        latitude: 40.8073738,
        longitude: -73.9608882,
        address: "Philosophy Hall, 1150 Amsterdam Ave, New York",
        neighborhood: "East Harlem",
        rating: 4.3,
        reviews: 75,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 19,
        name: "Winfield Street Coffee- 86th Street",
        latitude: 40.7776319,
        longitude: -73.9515642,
        address: "Q Line Subway Platform, 300 East 86th St, New York",
        neighborhood: "East Harlem",
        rating: 4.3,
        reviews: 61,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 20,
        name: "787 Coffee",
        latitude: 40.7422456,
        longitude: -73.9831245,
        address: "100 Lexington Ave, New York",
        neighborhood: "Greenwich Village",
        rating: 4.9,
        reviews: 2366,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 21,
        name: "787 Coffee",
        latitude: 40.7274105,
        longitude: -73.9887923,
        address: "101 2nd Ave, New York",
        neighborhood: "Greenwich Village",
        rating: 4.9,
        reviews: 1803,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 22,
        name: "A-Frame Cafe",
        latitude: 40.7242833,
        longitude: -73.9967369,
        address: "114 Crosby St, New York",
        neighborhood: "Greenwich Village",
        rating: 4.5,
        reviews: 32,
        features: ["coffee","wifi","food","outdoor seating"]
    },
    {
        id: 23,
        name: "King's Street Coffee",
        latitude: 40.7478184,
        longitude: -73.9906072,
        address: "121 W 30th St, New York",
        neighborhood: "Greenwich Village",
        rating: 4.6,
        reviews: 436,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 24,
        name: "Intelligentsia Coffee High Line Hotel Coffeebar",
        latitude: 40.7458671,
        longitude: -74.0051155,
        address: "High Line Hotel 180 10th Ave at, W 20th St, New York",
        neighborhood: "Greenwich Village",
        rating: 4.5,
        reviews: 610,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 25,
        name: "Niko Coffee + more",
        latitude: 40.805429,
        longitude: -73.962415,
        address: "1090 Amsterdam Ave, New York",
        neighborhood: "Harlem",
        rating: 4.0,
        reviews: 28,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 26,
        name: "Kuro Kuma",
        latitude: 40.8140525,
        longitude: -73.9600376,
        address: "121 La Salle St, New York",
        neighborhood: "Harlem",
        rating: 4.7,
        reviews: 289,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 27,
        name: "Plowshares Coffee Roasters",
        latitude: 40.8137198,
        longitude: -73.9556886,
        address: "1351 Amsterdam Ave, New York",
        neighborhood: "Harlem",
        rating: 4.5,
        reviews: 184,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 28,
        name: "Fumo Caffe e Vino",
        latitude: 40.8217389,
        longitude: -73.9503784,
        address: "1608 Amsterdam Ave, New York",
        neighborhood: "Harlem",
        rating: 4.8,
        reviews: 28,
        features: ["coffee","wifi","food","outdoor seating"]
    },
    {
        id: 29,
        name: "Cafe One",
        latitude: 40.8220851,
        longitude: -73.9496565,
        address: "1619 Amsterdam Ave, New York",
        neighborhood: "Harlem",
        rating: 4.6,
        reviews: 520,
        features: ["coffee","wifi","food","outdoor seating"]
    },
    {
        id: 30,
        name: "The Oma, Shop I",
        latitude: 40.8247837,
        longitude: -73.947723,
        address: "1707 Amsterdam Ave, New York",
        neighborhood: "Harlem",
        rating: 4.7,
        reviews: 87,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 31,
        name: "Manhattanville Coffee",
        latitude: 40.8295038,
        longitude: -73.9447477,
        address: "1850 Amsterdam Ave, New York",
        neighborhood: "Harlem",
        rating: 4.7,
        reviews: 88,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 32,
        name: "Super Nice Coffee and Bakery",
        latitude: 40.8015384,
        longitude: -73.9645052,
        address: "196 W 108th St, New York",
        neighborhood: "Harlem",
        rating: 4.5,
        reviews: 265,
        features: ["coffee","wifi","food","outdoor seating"]
    },
    {
        id: 33,
        name: "The Monkey Cup",
        latitude: 40.8046374,
        longitude: -73.9511804,
        address: "1965 Adam Clayton Powell Jr Blvd, New York",
        neighborhood: "Harlem",
        rating: 4.7,
        reviews: 671,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 34,
        name: "PROOF Coffee Roasters",
        latitude: 40.8149635,
        longitude: -73.9442779,
        address: "2286 Adam Clayton Powell Jr Blvd, New York",
        neighborhood: "Harlem",
        rating: 4.5,
        reviews: 287,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 35,
        name: "The Oma, Shop II Coffee+ Lifestyle",
        latitude: 40.8237017,
        longitude: -73.9410627,
        address: "2754 Frederick Douglass Blvd, New York",
        neighborhood: "Harlem",
        rating: 4.9,
        reviews: 32,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 36,
        name: "Common Good Harlem",
        latitude: 40.8254414,
        longitude: -73.9404457,
        address: "2801 Frederick Douglass Blvd, New York",
        neighborhood: "Harlem",
        rating: 4.8,
        reviews: 281,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 37,
        name: "Qahwah House - Broadway",
        latitude: 40.8052305,
        longitude: -73.9663752,
        address: "2869 Broadway, New York",
        neighborhood: "Harlem",
        rating: 4.8,
        reviews: 364,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 38,
        name: "Oren's Coffee",
        latitude: 40.8055942,
        longitude: -73.965337,
        address: "2882 Broadway, New York",
        neighborhood: "Harlem",
        rating: 3.9,
        reviews: 142,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 39,
        name: "Oren's Coffee",
        latitude: 40.8055942,
        longitude: -73.965337,
        address: "2882 Broadway, New York",
        neighborhood: "Harlem",
        rating: 3.9,
        reviews: 142,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 40,
        name: "The Chipped Cup",
        latitude: 40.8285897,
        longitude: -73.9485581,
        address: "3610 Broadway, New York",
        neighborhood: "Harlem",
        rating: 4.6,
        reviews: 841,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 41,
        name: "Superhet Coffee",
        latitude: 40.8053444,
        longitude: -73.9563327,
        address: "390 Manhattan Ave, New York",
        neighborhood: "Harlem",
        rating: 4.8,
        reviews: 31,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 42,
        name: "Red Kup",
        latitude: 40.8243284,
        longitude: -73.9447721,
        address: "701 St Nicholas Ave, New York",
        neighborhood: "Harlem",
        rating: 4.8,
        reviews: 148,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 43,
        name: "Hamilton Underground",
        latitude: 40.8262927,
        longitude: -73.9435207,
        address: "761 St Nicholas Ave, New York",
        neighborhood: "Harlem",
        rating: 4.9,
        reviews: 61,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 44,
        name: "The Clubhouse Cafe",
        latitude: 40.8261235,
        longitude: -73.9265912,
        address: "812 River Ave, Bronx",
        neighborhood: "Harlem",
        rating: 4.8,
        reviews: 72,
        features: ["coffee","wifi","food","outdoor seating"]
    },
    {
        id: 45,
        name: "City Coffee Bar",
        latitude: 40.7984838,
        longitude: -73.9636193,
        address: "914 Columbus Ave, New York",
        neighborhood: "Harlem",
        rating: 4.8,
        reviews: 185,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 46,
        name: "Variety Coffee",
        latitude: 40.806943,
        longitude: -73.9639479,
        address: "Alfred Lerner Hall, 2920 Broadway #2E, New York",
        neighborhood: "Harlem",
        rating: NaN,
        reviews: NaN,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 47,
        name: "ˈneɪ.bər.hʊd /neighborhood/ Coffee Shop",
        latitude: 40.7258034,
        longitude: -74.0019878,
        address: "107 Thompson St, New York",
        neighborhood: "Lower Manhattan",
        rating: 4.9,
        reviews: 44,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 48,
        name: "Voyager Espresso",
        latitude: 40.7088418,
        longitude: -74.0070094,
        address: "110 William St Lower Level, New York",
        neighborhood: "Lower Manhattan",
        rating: 4.8,
        reviews: 421,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 49,
        name: "No Plates Coffee",
        latitude: 40.7098478,
        longitude: -74.009123,
        address: "12 John St, New York",
        neighborhood: "Lower Manhattan",
        rating: 5.0,
        reviews: 110,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 50,
        name: "Café Grumpy - Lower East Side",
        latitude: 40.7151259,
        longitude: -73.9901558,
        address: "13 Essex St, New York",
        neighborhood: "Lower Manhattan",
        rating: 4.3,
        reviews: 213,
        features: ["coffee","wifi","food","outdoor seating"]
    },
    {
        id: 51,
        name: "Ten Thousand Coffee",
        latitude: 40.7075417,
        longitude: -74.0111541,
        address: "14 Wall St, New York",
        neighborhood: "Lower Manhattan",
        rating: 4.2,
        reviews: 215,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 52,
        name: "Interlude Coffee & Tea",
        latitude: 40.7210615,
        longitude: -74.0086055,
        address: "145 Hudson St, New York",
        neighborhood: "Lower Manhattan",
        rating: 4.7,
        reviews: 225,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 53,
        name: "Nako",
        latitude: 40.6931936,
        longitude: -73.9987459,
        address: "18 Columbia Pl, Brooklyn",
        neighborhood: "Lower Manhattan",
        rating: 4.8,
        reviews: 65,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 54,
        name: "Urban Backyard",
        latitude: 40.7208064,
        longitude: -73.9966015,
        address: "180 Mulberry St, New York",
        neighborhood: "Lower Manhattan",
        rating: 4.8,
        reviews: 598,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 55,
        name: "Mermaid Coffee",
        latitude: 40.7104317,
        longitude: -74.009303,
        address: "200 Broadway, New York",
        neighborhood: "Lower Manhattan",
        rating: 4.2,
        reviews: 6,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 56,
        name: "ENLY",
        latitude: 40.722527,
        longitude: -73.995468,
        address: "227 Mott St, New York",
        neighborhood: "Lower Manhattan",
        rating: 4.4,
        reviews: 347,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 57,
        name: "La Colombe Coffee Workshop",
        latitude: 40.7239846,
        longitude: -73.9964056,
        address: "270 Lafayette St, New York",
        neighborhood: "Lower Manhattan",
        rating: 4.3,
        reviews: 702,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 58,
        name: "Kaffe Landskap",
        latitude: 40.7208984,
        longitude: -74.0097729,
        address: "401 Greenwich St, New York",
        neighborhood: "Lower Manhattan",
        rating: 4.2,
        reviews: 386,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 59,
        name: "Three Jewels Café",
        latitude: 40.726356,
        longitude: -73.991152,
        address: "5 E 3rd St FRNT 1, New York",
        neighborhood: "Lower Manhattan",
        rating: 4.8,
        reviews: 149,
        features: ["coffee","wifi","food","outdoor seating"]
    },
    {
        id: 60,
        name: "La Colombe Coffee Workshop",
        latitude: 40.7056386,
        longitude: -74.0083564,
        address: "67 Wall St, New York",
        neighborhood: "Lower Manhattan",
        rating: 4.5,
        reviews: 548,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 61,
        name: "Black Fox Coffee",
        latitude: 40.7065047,
        longitude: -74.0077715,
        address: "70 Pine St, New York",
        neighborhood: "Lower Manhattan",
        rating: 4.5,
        reviews: 1081,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 62,
        name: "Mean Bean Cafe",
        latitude: 40.7187485,
        longitude: -73.989578,
        address: "85 Delancey St, New York",
        neighborhood: "Lower Manhattan",
        rating: 4.6,
        reviews: 11,
        features: ["coffee","wifi","food","outdoor seating"]
    },
    {
        id: 63,
        name: "T Café",
        latitude: 40.7062237,
        longitude: -74.0023067,
        address: "96 South St, New York",
        neighborhood: "Lower Manhattan",
        rating: 4.2,
        reviews: 60,
        features: ["coffee","wifi","food","outdoor seating"]
    },
    {
        id: 64,
        name: "le Cafe Coffee",
        latitude: 40.7115663,
        longitude: -74.0114261,
        address: "LL4350, 185 Greenwich St, New York",
        neighborhood: "Lower Manhattan",
        rating: 3.8,
        reviews: 19,
        features: ["coffee","wifi","food","outdoor seating"]
    },
    {
        id: 65,
        name: "WFM Coffee Bar",
        latitude: 40.7685526,
        longitude: -73.9831866,
        address: "10 Columbus Cir Ste Sc101, New York",
        neighborhood: "Midtown North",
        rating: 3.2,
        reviews: 5,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 66,
        name: "Frisson Espresso",
        latitude: 40.7609093,
        longitude: -73.9889374,
        address: "10036 326 W 47th St, New York",
        neighborhood: "Midtown North",
        rating: 4.7,
        reviews: 1198,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 67,
        name: "Solid State Coffee",
        latitude: 40.7767764,
        longitude: -73.9796827,
        address: "104 W 71st St, New York",
        neighborhood: "Midtown North",
        rating: 4.7,
        reviews: 567,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 68,
        name: "Marathon Coffee",
        latitude: 40.7580295,
        longitude: -73.9628597,
        address: "1042 1st Ave, New York",
        neighborhood: "Midtown North",
        rating: 4.4,
        reviews: 28,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 69,
        name: "Gumption Coffee",
        latitude: 40.7569259,
        longitude: -73.983446,
        address: "106 W 45th St, New York",
        neighborhood: "Midtown North",
        rating: 4.5,
        reviews: 224,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 70,
        name: "Black Press Coffee",
        latitude: 40.7638398,
        longitude: -73.9647023,
        address: "1065 3rd Ave, New York",
        neighborhood: "Midtown North",
        rating: 4.4,
        reviews: 111,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 71,
        name: "Masseria Caffe & Bakery",
        latitude: 40.7607554,
        longitude: -73.9858962,
        address: "235 W 48th St, New York",
        neighborhood: "Midtown North",
        rating: 4.5,
        reviews: 364,
        features: ["coffee","wifi","food","outdoor seating"]
    },
    {
        id: 72,
        name: "787 coffee",
        latitude: 40.7597196,
        longitude: -73.987354,
        address: "245 W 46th St, New York",
        neighborhood: "Midtown North",
        rating: 4.9,
        reviews: 1836,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 73,
        name: "Ramini Espresso & cafe",
        latitude: 40.7540845,
        longitude: -73.9916851,
        address: "265 W 37th St, New York",
        neighborhood: "Midtown North",
        rating: 4.8,
        reviews: 304,
        features: ["coffee","wifi","food","outdoor seating"]
    },
    {
        id: 74,
        name: "Lucid Cafe",
        latitude: 40.7487442,
        longitude: -73.9778073,
        address: "311 Lexington Ave, New York",
        neighborhood: "Midtown North",
        rating: 4.5,
        reviews: 310,
        features: ["coffee","wifi","food","outdoor seating"]
    },
    {
        id: 75,
        name: "Deploy Coffee",
        latitude: 40.7454495,
        longitude: -73.9574782,
        address: "47-40 Center Blvd, Long Island City",
        neighborhood: "Midtown North",
        rating: 4.9,
        reviews: 132,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 76,
        name: "Gold coffee",
        latitude: 40.7451277,
        longitude: -73.9783508,
        address: "491 3rd Ave, New York",
        neighborhood: "Midtown North",
        rating: 4.9,
        reviews: 353,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 77,
        name: "Ground Central Coffee Company",
        latitude: 40.7530091,
        longitude: -73.9898267,
        address: "498 7th Ave, New York",
        neighborhood: "Midtown North",
        rating: 4.5,
        reviews: 259,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 78,
        name: "Cafe Aroma",
        latitude: 40.755952,
        longitude: -73.9941408,
        address: "502 9th Ave, New York",
        neighborhood: "Midtown North",
        rating: 4.6,
        reviews: 924,
        features: ["coffee","wifi","food","outdoor seating"]
    },
    {
        id: 79,
        name: "The Jolly Goat Coffee Bar",
        latitude: 40.7632559,
        longitude: -73.9939773,
        address: "515 W 47th St, New York",
        neighborhood: "Midtown North",
        rating: 4.5,
        reviews: 484,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 80,
        name: "Little Collins",
        latitude: 40.7523639,
        longitude: -73.9735114,
        address: "708 3rd Ave, New York",
        neighborhood: "Midtown North",
        rating: 4.6,
        reviews: 2323,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 81,
        name: "Afficionado Coffee Roasters",
        latitude: 40.7676039,
        longitude: -73.9931737,
        address: "750 11th Ave, New York",
        neighborhood: "Midtown North",
        rating: 4.5,
        reviews: 302,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 82,
        name: "Cafe Hatou",
        latitude: 40.7571905,
        longitude: -73.9691844,
        address: "Lower Level, 875 3rd Ave Store D, New York",
        neighborhood: "Midtown North",
        rating: 4.6,
        reviews: 38,
        features: ["coffee","wifi","food","outdoor seating"]
    },
    {
        id: 83,
        name: "Ralph's Coffee",
        latitude: 40.7401079,
        longitude: -73.9908573,
        address: "160 5th Ave, New York",
        neighborhood: "Midtown South",
        rating: 4.2,
        reviews: 560,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 84,
        name: "Radiant café",
        latitude: 40.734024,
        longitude: -74.0013903,
        address: "172 Waverly Pl, New York",
        neighborhood: "Midtown South",
        rating: 4.8,
        reviews: 262,
        features: ["coffee","wifi","food","outdoor seating"]
    },
    {
        id: 85,
        name: "St Kilda Coffee",
        latitude: 40.7590215,
        longitude: -73.9902705,
        address: "328 W 44th St, New York",
        neighborhood: "Midtown South",
        rating: 4.6,
        reviews: 659,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 86,
        name: "Aleef Cafe",
        latitude: 40.7561758,
        longitude: -73.9925797,
        address: "333 W 39th St, New York",
        neighborhood: "Midtown South",
        rating: 4.8,
        reviews: 481,
        features: ["coffee","wifi","food","outdoor seating"]
    },
    {
        id: 87,
        name: "ARVACI coffee",
        latitude: 40.7546716,
        longitude: -73.9940186,
        address: "340 W 37th St, New York",
        neighborhood: "Midtown South",
        rating: 4.7,
        reviews: 630,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 88,
        name: "Bird & Branch Coffee Roasters",
        latitude: 40.7602998,
        longitude: -73.9907758,
        address: "359 W 45th St, New York",
        neighborhood: "Midtown South",
        rating: 4.6,
        reviews: 806,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 89,
        name: "St Kilda Coffee",
        latitude: 40.7607877,
        longitude: -73.9906014,
        address: "374 W 46th St, New York",
        neighborhood: "Midtown South",
        rating: 4.6,
        reviews: 228,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 90,
        name: "Frisson Espresso 44",
        latitude: 40.760034,
        longitude: -73.9921323,
        address: "405 W 44th St, New York",
        neighborhood: "Midtown South",
        rating: 4.9,
        reviews: 350,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 91,
        name: "Black Fox Coffee",
        latitude: 40.7532346,
        longitude: -73.9982743,
        address: "438 W 33rd St, New York",
        neighborhood: "Midtown South",
        rating: 4.5,
        reviews: 212,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 92,
        name: "GRIND THE NYC COFFEE SHOP & BAGEL HOUSE",
        latitude: 40.75911,
        longitude: -73.9918724,
        address: "602 9th Ave, New York",
        neighborhood: "Midtown South",
        rating: 4.5,
        reviews: 847,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 93,
        name: "Oslo Coffee Roasters",
        latitude: 40.7605599,
        longitude: -73.9990525,
        address: "620 W 42nd St, New York",
        neighborhood: "Midtown South",
        rating: 4.5,
        reviews: 201,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 94,
        name: "Ground Central Coffee Company",
        latitude: 40.7474621,
        longitude: -73.9737215,
        address: "714 2nd Ave, New York",
        neighborhood: "Midtown South",
        rating: 4.4,
        reviews: 51,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 95,
        name: "Brewlita",
        latitude: 40.7225775,
        longitude: -73.9962468,
        address: "227 Mulberry St, New York",
        neighborhood: "SoHo / Nolita",
        rating: 4.7,
        reviews: 366,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 96,
        name: ":3Coffee | Flatiron",
        latitude: 40.7411056,
        longitude: -73.9919787,
        address: "29 W 21st St, New York",
        neighborhood: "SoHo / Nolita",
        rating: 4.6,
        reviews: 69,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 97,
        name: "Gemina Coffee Shop",
        latitude: 40.7306295,
        longitude: -73.9815209,
        address: "424 E 14th St, New York",
        neighborhood: "SoHo / Nolita",
        rating: 4.7,
        reviews: 131,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 98,
        name: "PROOF Coffee Roasters",
        latitude: 40.7399117,
        longitude: -73.9774474,
        address: "ENTRANCE IN PARK AREA, 335 E 27th St, New York",
        neighborhood: "SoHo / Nolita",
        rating: 4.5,
        reviews: 230,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 99,
        name: "Cafecito",
        latitude: 40.7185864,
        longitude: -73.9940512,
        address: "111 Chrystie St, New York",
        neighborhood: "Tribeca",
        rating: 4.5,
        reviews: 73,
        features: ["coffee","wifi","food","outdoor seating"]
    },
    {
        id: 100,
        name: "Cafe Atelier",
        latitude: 40.7195671,
        longitude: -74.0083683,
        address: "112 Hudson St, New York",
        neighborhood: "Tribeca",
        rating: 4.6,
        reviews: 188,
        features: ["coffee","wifi","food","outdoor seating"]
    },
    {
        id: 101,
        name: "Blank Street Coffee",
        latitude: 40.7140224,
        longitude: -74.0084821,
        address: "125 Church St, New York",
        neighborhood: "Tribeca",
        rating: 4.8,
        reviews: 107,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 102,
        name: "Poetica Coffee",
        latitude: 40.7285398,
        longitude: -73.9879491,
        address: "131 2nd Ave, New York",
        neighborhood: "Tribeca",
        rating: 4.4,
        reviews: 140,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 103,
        name: "Coffee Project New York | Financial District",
        latitude: 40.7071267,
        longitude: -74.0050419,
        address: "135 John St, New York",
        neighborhood: "Tribeca",
        rating: 4.5,
        reviews: 108,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 104,
        name: "Birch Coffee",
        latitude: 40.7142964,
        longitude: -74.0087014,
        address: "136 Church St, New York",
        neighborhood: "Tribeca",
        rating: 4.6,
        reviews: 35,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 105,
        name: "Variety Coffee Roasters",
        latitude: 40.7113438,
        longitude: -74.0063219,
        address: "140 Nassau St, New York",
        neighborhood: "Tribeca",
        rating: 4.4,
        reviews: 243,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 106,
        name: "COSMIC CAT COFFEE AND ESPRESSO",
        latitude: 40.7227153,
        longitude: -73.9846926,
        address: "170E E 2nd St, New York",
        neighborhood: "Tribeca",
        rating: 4.9,
        reviews: 128,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 107,
        name: "Sui Café • Coffee Studio",
        latitude: 40.7259494,
        longitude: -74.0036613,
        address: "180 6th Ave, New York",
        neighborhood: "Tribeca",
        rating: 4.8,
        reviews: 29,
        features: ["coffee","wifi","food","outdoor seating"]
    },
    {
        id: 108,
        name: "Blank Street Coffee",
        latitude: 40.7265166,
        longitude: -74.0019816,
        address: "181 Prince St, New York",
        neighborhood: "Tribeca",
        rating: 4.4,
        reviews: 205,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 109,
        name: "Artbean Coffee Roasters",
        latitude: 40.7147104,
        longitude: -73.9981425,
        address: "19 Doyers St, New York",
        neighborhood: "Tribeca",
        rating: 4.7,
        reviews: 302,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 110,
        name: "PlantShed Cafe",
        latitude: 40.7312764,
        longitude: -73.986102,
        address: "193 2nd Ave, New York",
        neighborhood: "Tribeca",
        rating: 4.2,
        reviews: 72,
        features: ["coffee","wifi","food","outdoor seating"]
    },
    {
        id: 111,
        name: "% Arabica",
        latitude: 40.7026068,
        longitude: -73.9941427,
        address: "20 Old Fulton St, Brooklyn",
        neighborhood: "Tribeca",
        rating: 4.4,
        reviews: 1288,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 112,
        name: "Blank Street Coffee",
        latitude: 40.7225679,
        longitude: -73.9971817,
        address: "236 Lafayette St, New York",
        neighborhood: "Tribeca",
        rating: 4.0,
        reviews: 160,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 113,
        name: "Third Rail Coffee",
        latitude: 40.7299991,
        longitude: -73.9995587,
        address: "240 Sullivan St, New York",
        neighborhood: "Tribeca",
        rating: 4.2,
        reviews: 362,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 114,
        name: "Koré Coffee",
        latitude: 40.7161762,
        longitude: -73.9971056,
        address: "26A Elizabeth St, New York",
        neighborhood: "Tribeca",
        rating: 4.8,
        reviews: 445,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 115,
        name: "WFM Coffee Bar",
        latitude: 40.7158966,
        longitude: -74.0128357,
        address: "270 Greenwich St, New York",
        neighborhood: "Tribeca",
        rating: 4.3,
        reviews: 66,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 116,
        name: "drip coffee makers",
        latitude: 40.703786,
        longitude: -74.0077143,
        address: "32 Old Slip, New York",
        neighborhood: "Tribeca",
        rating: 4.3,
        reviews: 12,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 117,
        name: "Sawada Coffee",
        latitude: 40.7181697,
        longitude: -74.0018976,
        address: "33 Cortlandt Alley, New York",
        neighborhood: "Tribeca",
        rating: 4.6,
        reviews: 187,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 118,
        name: "The Lost Draft",
        latitude: 40.7208367,
        longitude: -73.9972249,
        address: "398 Broome St, New York",
        neighborhood: "Tribeca",
        rating: 4.6,
        reviews: 553,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 119,
        name: "Ground Support Cafe",
        latitude: 40.7242903,
        longitude: -74.001961,
        address: "399 W Broadway, New York",
        neighborhood: "Tribeca",
        rating: 4.4,
        reviews: 889,
        features: ["coffee","wifi","food","outdoor seating"]
    },
    {
        id: 120,
        name: "Merriweather Coffee + Kitchen",
        latitude: 40.7305704,
        longitude: -74.0066289,
        address: "428 Hudson St, New York",
        neighborhood: "Tribeca",
        rating: 4.6,
        reviews: 448,
        features: ["coffee","wifi","food","outdoor seating"]
    },
    {
        id: 121,
        name: "Suited NYC",
        latitude: 40.7092869,
        longitude: -74.0078767,
        address: "45 John St, New York",
        neighborhood: "Tribeca",
        rating: 4.7,
        reviews: 572,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 122,
        name: "Coffee Project New York | Tribeca",
        latitude: 40.7236946,
        longitude: -74.0105919,
        address: "450 Washington St, New York",
        neighborhood: "Tribeca",
        rating: 4.8,
        reviews: 11,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 123,
        name: "Simpl Coffee",
        latitude: 40.7092885,
        longitude: -74.0088172,
        address: "59 Nassau St, New York",
        neighborhood: "Tribeca",
        rating: 4.9,
        reviews: 578,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 124,
        name: "787 Coffee",
        latitude: 40.7034852,
        longitude: -74.0108313,
        address: "66 Pearl St, New York",
        neighborhood: "Tribeca",
        rating: 4.8,
        reviews: 2778,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 125,
        name: "Coffee And Caviar",
        latitude: 40.7170313,
        longitude: -74.0056975,
        address: "71 Worth St, New York",
        neighborhood: "Tribeca",
        rating: 4.9,
        reviews: 55,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 126,
        name: "% Arabica New York Nolita",
        latitude: 40.7225128,
        longitude: -73.9938232,
        address: "8 Prince St, New York",
        neighborhood: "Tribeca",
        rating: 4.3,
        reviews: 254,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 127,
        name: "Abraço",
        latitude: 40.7272981,
        longitude: -73.9862102,
        address: "81 E 7th St, New York",
        neighborhood: "Tribeca",
        rating: 4.3,
        reviews: 922,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 128,
        name: "Roasting Plant Coffee",
        latitude: 40.7177965,
        longitude: -73.990579,
        address: "81 Orchard St, New York",
        neighborhood: "Tribeca",
        rating: 4.6,
        reviews: 253,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 129,
        name: "787 Coffee",
        latitude: 40.7165872,
        longitude: -74.0048064,
        address: "93 Worth St, New York",
        neighborhood: "Tribeca",
        rating: 4.9,
        reviews: 2253,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 130,
        name: "Kona Coffee Roasters | Midtown",
        latitude: 40.7513739,
        longitude: -73.9785636,
        address: "100 Park Ave, New York",
        neighborhood: "Union Square",
        rating: 4.4,
        reviews: 282,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 131,
        name: "Saltwater Coffee",
        latitude: 40.732672,
        longitude: -73.9997589,
        address: "126 Waverly Pl, New York",
        neighborhood: "Union Square",
        rating: 4.3,
        reviews: 153,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 132,
        name: "BUNGEE Coffee",
        latitude: 40.7224318,
        longitude: -73.992346,
        address: "13 Stanton St, New York",
        neighborhood: "Union Square",
        rating: 4.7,
        reviews: 46,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 133,
        name: "Stone Street Coffee",
        latitude: 40.7436409,
        longitude: -74.0031995,
        address: "134 9th Ave, New York",
        neighborhood: "Union Square",
        rating: 4.4,
        reviews: 29,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 134,
        name: "Everyman Espresso",
        latitude: 40.732713,
        longitude: -73.9883255,
        address: "136 E 13th St, New York",
        neighborhood: "Union Square",
        rating: 4.4,
        reviews: 479,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 135,
        name: "Café Integral",
        latitude: 40.7203886,
        longitude: -73.9951742,
        address: "149 Elizabeth St, New York",
        neighborhood: "Union Square",
        rating: 4.5,
        reviews: 457,
        features: ["coffee","wifi","food","outdoor seating"]
    },
    {
        id: 136,
        name: "A'more Caffe",
        latitude: 40.7230448,
        longitude: -73.9854791,
        address: "150 E 2nd St, New York",
        neighborhood: "Union Square",
        rating: 4.8,
        reviews: 113,
        features: ["coffee","wifi","food","outdoor seating"]
    },
    {
        id: 137,
        name: "La Cabra Bakery",
        latitude: 40.7294459,
        longitude: -73.9868353,
        address: "152 2nd Ave, New York",
        neighborhood: "Union Square",
        rating: 4.7,
        reviews: 1236,
        features: ["coffee","wifi","food","outdoor seating"]
    },
    {
        id: 138,
        name: "ARVACI coffee",
        latitude: 40.7453438,
        longitude: -73.9795096,
        address: "152 E 33rd St, New York",
        neighborhood: "Union Square",
        rating: 4.8,
        reviews: 323,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 139,
        name: "Coffee Project New York | Chelsea",
        latitude: 40.7418278,
        longitude: -73.9970885,
        address: "155 7th Ave, New York",
        neighborhood: "Union Square",
        rating: 4.4,
        reviews: 307,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 140,
        name: "787 Coffee",
        latitude: 40.7298164,
        longitude: -73.9871495,
        address: "159 2nd Ave, corner of, E 10th St, New York",
        neighborhood: "Union Square",
        rating: 4.8,
        reviews: 1998,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 141,
        name: "Café Lyria",
        latitude: 40.7258264,
        longitude: -73.9954461,
        address: "166 Crosby St, New York",
        neighborhood: "Union Square",
        rating: 4.6,
        reviews: 437,
        features: ["coffee","wifi","food","outdoor seating"]
    },
    {
        id: 142,
        name: "Ludlow Coffee Supply",
        latitude: 40.7216799,
        longitude: -73.9873886,
        address: "176 Ludlow St, New York",
        neighborhood: "Union Square",
        rating: 4.3,
        reviews: 525,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 143,
        name: "Stumptown Coffee Roasters",
        latitude: 40.7457399,
        longitude: -73.9882272,
        address: "18 W 29th St, New York",
        neighborhood: "Union Square",
        rating: 4.5,
        reviews: 1615,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 144,
        name: "Kona Coffee Roasters | Chelsea",
        latitude: 40.7429668,
        longitude: -73.9966854,
        address: "188 7th Ave, New York",
        neighborhood: "Union Square",
        rating: 4.2,
        reviews: 158,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 145,
        name: "787 Coffee",
        latitude: 40.7340226,
        longitude: -74.0040107,
        address: "204 W 10th St, New York",
        neighborhood: "Union Square",
        rating: 4.9,
        reviews: 2466,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 146,
        name: "Gotham Coffee Roasters",
        latitude: 40.739862,
        longitude: -73.992693,
        address: "23 W 19th St, New York",
        neighborhood: "Union Square",
        rating: 4.5,
        reviews: 236,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 147,
        name: "Oslo Coffee Roasters (West Village)",
        latitude: 40.7338112,
        longitude: -74.005472,
        address: "236 W 10th St, New York",
        neighborhood: "Union Square",
        rating: 4.7,
        reviews: 207,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 148,
        name: "Coffee Project New York | East Village",
        latitude: 40.7270678,
        longitude: -73.9893902,
        address: "239 E 5th St, New York",
        neighborhood: "Union Square",
        rating: 4.7,
        reviews: 771,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 149,
        name: "Kobrick Coffee Co.",
        latitude: 40.7402731,
        longitude: -74.0055792,
        address: "24 9th Ave, New York",
        neighborhood: "Union Square",
        rating: 4.3,
        reviews: 1423,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 150,
        name: "Sip Coffee",
        latitude: 40.7473825,
        longitude: -73.9958787,
        address: "242 W 27th St, New York",
        neighborhood: "Union Square",
        rating: 4.8,
        reviews: 293,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 151,
        name: "787 Coffee Co.",
        latitude: 40.7493629,
        longitude: -73.9942691,
        address: "251 W 30th St, New York",
        neighborhood: "Union Square",
        rating: 4.9,
        reviews: 3136,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 152,
        name: "787 Coffee",
        latitude: 40.7400325,
        longitude: -74.0015893,
        address: "256 W 15th St, New York",
        neighborhood: "Union Square",
        rating: 4.9,
        reviews: 2333,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 153,
        name: "Absolute Coffee",
        latitude: 40.7313686,
        longitude: -74.0028134,
        address: "259 Bleecker St, New York",
        neighborhood: "Union Square",
        rating: 4.8,
        reviews: 26,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 154,
        name: "Variety Coffee Roasters",
        latitude: 40.7451674,
        longitude: -73.9945849,
        address: "261 7th Ave, New York",
        neighborhood: "Union Square",
        rating: 4.4,
        reviews: 880,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 155,
        name: "La Cabra",
        latitude: 40.72431,
        longitude: -73.9962,
        address: "284 Lafayette St, New York",
        neighborhood: "Union Square",
        rating: 4.5,
        reviews: 577,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 156,
        name: "Now or Never Coffee",
        latitude: 40.7229055,
        longitude: -74.0045789,
        address: "30 Grand St, New York",
        neighborhood: "Union Square",
        rating: 4.5,
        reviews: 370,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 157,
        name: "Stumptown Coffee Roasters",
        latitude: 40.7328313,
        longitude: -73.9979754,
        address: "30 W 8th St, New York",
        neighborhood: "Union Square",
        rating: 4.4,
        reviews: 1392,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 158,
        name: "787 Coffee",
        latitude: 40.739879,
        longitude: -74.0033107,
        address: "310 W 14th St, New York",
        neighborhood: "Union Square",
        rating: 4.9,
        reviews: 1905,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 159,
        name: "Terremoto Coffee",
        latitude: 40.7408448,
        longitude: -74.0033272,
        address: "328 W 15th St, New York",
        neighborhood: "Union Square",
        rating: 4.5,
        reviews: 522,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 160,
        name: "Saltwater Coffee",
        latitude: 40.7303122,
        longitude: -73.983956,
        address: "345 E 12th St, New York",
        neighborhood: "Union Square",
        rating: 4.5,
        reviews: 367,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 161,
        name: "The Walkers Espresso",
        latitude: 40.737606,
        longitude: -74.0000955,
        address: "37 7th Ave, New York",
        neighborhood: "Union Square",
        rating: 5.0,
        reviews: 138,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 162,
        name: "Copper Mug Coffee",
        latitude: 40.7465799,
        longitude: -73.9882242,
        address: "38 W 30th St, New York",
        neighborhood: "Union Square",
        rating: 4.8,
        reviews: 661,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 163,
        name: "Le Cafe Coffee",
        latitude: 40.7500039,
        longitude: -73.992123,
        address: "392 7th Ave, New York",
        neighborhood: "Union Square",
        rating: 4.1,
        reviews: 97,
        features: ["coffee","wifi","food","outdoor seating"]
    },
    {
        id: 164,
        name: "Paper Coffee",
        latitude: 40.7462091,
        longitude: -73.9895129,
        address: "44 W 29th St, New York",
        neighborhood: "Union Square",
        rating: 4.1,
        reviews: 616,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 165,
        name: "Felix Roasting Co.",
        latitude: 40.7450345,
        longitude: -73.9831581,
        address: "450 Park Ave S, New York",
        neighborhood: "Union Square",
        rating: 4.3,
        reviews: 683,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 166,
        name: "Blackstone Coffee Roaster",
        latitude: 40.7332423,
        longitude: -74.0062034,
        address: "502 Hudson St, New York",
        neighborhood: "Union Square",
        rating: 4.7,
        reviews: 285,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 167,
        name: "Felix Roasting Co.",
        latitude: 40.7263724,
        longitude: -74.0089026,
        address: "525 Greenwich St, New York",
        neighborhood: "Union Square",
        rating: 4.3,
        reviews: 96,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 168,
        name: "Cafe by the Girls Colombian Coffee",
        latitude: 40.7485687,
        longitude: -74.0055397,
        address: "537a W 23rd St, New York",
        neighborhood: "Union Square",
        rating: 4.5,
        reviews: 164,
        features: ["coffee","wifi","food","outdoor seating"]
    },
    {
        id: 169,
        name: "Kona Coffee Roasters | East Village",
        latitude: 40.7258692,
        longitude: -73.9898686,
        address: "57 2nd Ave, New York",
        neighborhood: "Union Square",
        rating: 4.4,
        reviews: 325,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 170,
        name: "Charlotte Cafe",
        latitude: 40.744364,
        longitude: -73.9765009,
        address: "605 2nd Ave, New York",
        neighborhood: "Union Square",
        rating: 4.9,
        reviews: 821,
        features: ["coffee","wifi","food","outdoor seating"]
    },
    {
        id: 171,
        name: "Starbucks Reserve Roastery New York",
        latitude: 40.7415944,
        longitude: -74.0051549,
        address: "61 9th Ave, New York",
        neighborhood: "Union Square",
        rating: 4.3,
        reviews: 5916,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 172,
        name: "Cafe Luna",
        latitude: 40.7383306,
        longitude: -74.0053786,
        address: "628 Hudson St, New York",
        neighborhood: "Union Square",
        rating: 4.6,
        reviews: 574,
        features: ["coffee","wifi","food","outdoor seating"]
    },
    {
        id: 173,
        name: "Foreigner NYC",
        latitude: 40.7413027,
        longitude: -73.9934364,
        address: "64 W 21st St, New York",
        neighborhood: "Union Square",
        rating: 4.2,
        reviews: 117,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 174,
        name: "Cafe La Fe, coffee shop",
        latitude: 40.7235521,
        longitude: -73.9888109,
        address: "70 E 1st St, New York",
        neighborhood: "Union Square",
        rating: 4.9,
        reviews: 117,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 175,
        name: "The Lazy Llama Coffee Bar",
        latitude: 40.7234847,
        longitude: -73.9886798,
        address: "72 E 1st St, New York",
        neighborhood: "Union Square",
        rating: 4.6,
        reviews: 352,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 176,
        name: "787 Coffee",
        latitude: 40.7244179,
        longitude: -74.0029292,
        address: "72 Thompson St, New York",
        neighborhood: "Union Square",
        rating: 4.8,
        reviews: 1510,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 177,
        name: "Culture Espresso",
        latitude: 40.7520746,
        longitude: -73.9857387,
        address: "72 W 38th St, New York",
        neighborhood: "Union Square",
        rating: 4.6,
        reviews: 1884,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 178,
        name: "Pulley Coffee Bar",
        latitude: 40.7424155,
        longitude: -74.0062311,
        address: "75 9th Ave, New York",
        neighborhood: "Union Square",
        rating: 3.4,
        reviews: 81,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 179,
        name: "drip coffee makers",
        latitude: 40.7232325,
        longitude: -74.0064671,
        address: "75 Varick St, New York",
        neighborhood: "Union Square",
        rating: 4.7,
        reviews: 65,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 180,
        name: "Terremoto Coffee",
        latitude: 40.7398638,
        longitude: -74.0021836,
        address: "80 8th Ave, New York",
        neighborhood: "Union Square",
        rating: 4.7,
        reviews: 17,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 181,
        name: "Sammy L Coffee",
        latitude: 40.7316812,
        longitude: -73.9879701,
        address: "83 3rd Ave, New York",
        neighborhood: "Union Square",
        rating: 4.5,
        reviews: 205,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 182,
        name: "Gumption Coffee",
        latitude: 40.7407668,
        longitude: -73.9891279,
        address: "940 Broadway, New York",
        neighborhood: "Union Square",
        rating: 3.9,
        reviews: 50,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 183,
        name: "Yanni's Coffee",
        latitude: 40.739821,
        longitude: -73.9989877,
        address: "96 7th Ave, New York",
        neighborhood: "Union Square",
        rating: 4.7,
        reviews: 369,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 184,
        name: "Drip Drop Café, coffee shop",
        latitude: 40.7254115,
        longitude: -74.002083,
        address: "98 Thompson St, New York",
        neighborhood: "Union Square",
        rating: 4.8,
        reviews: 607,
        features: ["coffee","wifi","food","outdoor seating"]
    },
    {
        id: 185,
        name: "Tenz Espresso Bar",
        latitude: 40.7593283,
        longitude: -73.9624035,
        address: "1071A 1st Ave, New York",
        neighborhood: "Upper East Side",
        rating: 5.0,
        reviews: 170,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 186,
        name: "Blank Street Coffee",
        latitude: 40.7756985,
        longitude: -73.9582274,
        address: "1173 Lexington Ave, New York",
        neighborhood: "Upper East Side",
        rating: 4.2,
        reviews: 114,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 187,
        name: "Birch Coffee",
        latitude: 40.7804218,
        longitude: -73.9534302,
        address: "171 E 88th St, New York",
        neighborhood: "Upper East Side",
        rating: 4.5,
        reviews: 365,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 188,
        name: "Café Blériot XI",
        latitude: 40.7762309,
        longitude: -73.9544046,
        address: "226 E 83rd St, New York",
        neighborhood: "Upper East Side",
        rating: 4.6,
        reviews: 281,
        features: ["coffee","wifi","food","outdoor seating"]
    },
    {
        id: 189,
        name: "Madame Bonté Café",
        latitude: 40.7760219,
        longitude: -73.9519287,
        address: "318 E 84th St, New York",
        neighborhood: "Upper East Side",
        rating: 4.5,
        reviews: 295,
        features: ["coffee","wifi","food","outdoor seating"]
    },
    {
        id: 190,
        name: "Greenport Cafe",
        latitude: 40.7600502,
        longitude: -73.9632614,
        address: "322 E 59th St, New York",
        neighborhood: "Upper East Side",
        rating: 4.3,
        reviews: 32,
        features: ["coffee","wifi","food","outdoor seating"]
    },
    {
        id: 191,
        name: "Fellini Coffee - Upper West",
        latitude: 40.7871044,
        longitude: -73.9751788,
        address: "523 Amsterdam Ave, New York",
        neighborhood: "Upper East Side",
        rating: 4.3,
        reviews: 26,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 192,
        name: "Devoción",
        latitude: 40.758132,
        longitude: -73.9713838,
        address: "600 Lexington Ave, New York",
        neighborhood: "Upper East Side",
        rating: 4.6,
        reviews: 262,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 193,
        name: "Malta Coffee",
        latitude: 40.7720733,
        longitude: -73.9608146,
        address: "1045 Lexington Ave, New York",
        neighborhood: "Upper Midtown",
        rating: 4.6,
        reviews: 79,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 194,
        name: "Daniel's Coffee and More",
        latitude: 40.7636529,
        longitude: -73.9653095,
        address: "1050 3rd Ave # 2b, New York",
        neighborhood: "Upper Midtown",
        rating: 4.4,
        reviews: 144,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 195,
        name: "Picky Barista",
        latitude: 40.7773515,
        longitude: -73.9573309,
        address: "1220 Lexington Ave, New York",
        neighborhood: "Upper Midtown",
        rating: 4.5,
        reviews: 294,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 196,
        name: "Le Reveil Coffee",
        latitude: 40.7672009,
        longitude: -73.9593226,
        address: "1322 2nd Ave, New York",
        neighborhood: "Upper Midtown",
        rating: 4.4,
        reviews: 293,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 197,
        name: "Ground Central Coffee Company",
        latitude: 40.7611903,
        longitude: -73.9817874,
        address: "138 W 51st St, New York",
        neighborhood: "Upper Midtown",
        rating: 4.3,
        reviews: 175,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 198,
        name: "Ten Thousand Coffee",
        latitude: 40.7532395,
        longitude: -73.9869855,
        address: "1410 Broadway Unit 105, New York",
        neighborhood: "Upper Midtown",
        rating: 4.2,
        reviews: 627,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 199,
        name: "Le Cafe Coffee",
        latitude: 40.7652942,
        longitude: -73.9767197,
        address: "1427 6th Ave, New York",
        neighborhood: "Upper Midtown",
        rating: 4.7,
        reviews: 92,
        features: ["coffee","wifi","food","outdoor seating"]
    },
    {
        id: 200,
        name: "Zuri Coffee",
        latitude: 40.7700697,
        longitude: -73.9516199,
        address: "1443 York Ave, New York",
        neighborhood: "Upper Midtown",
        rating: 4.5,
        reviews: 45,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 201,
        name: "Green Lane Coffee",
        latitude: 40.7744557,
        longitude: -73.95093,
        address: "1582 1st Ave, New York",
        neighborhood: "Upper Midtown",
        rating: 4.8,
        reviews: 136,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 202,
        name: "Sebastian's Cafe & Creamery",
        latitude: 40.7779265,
        longitude: -73.9489813,
        address: "1685 1st Ave, New York",
        neighborhood: "Upper Midtown",
        rating: 4.5,
        reviews: 35,
        features: ["coffee","wifi","food","outdoor seating"]
    },
    {
        id: 203,
        name: "JJ Brown Cup",
        latitude: 40.7795257,
        longitude: -73.9507686,
        address: "1707 2nd Ave, New York",
        neighborhood: "Upper Midtown",
        rating: 4.5,
        reviews: 95,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 204,
        name: "KEEMOFF Coffee",
        latitude: 40.780303,
        longitude: -73.9465784,
        address: "1764 1st Ave, New York",
        neighborhood: "Upper Midtown",
        rating: 4.7,
        reviews: 39,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 205,
        name: "Pavé",
        latitude: 40.7564389,
        longitude: -73.9802678,
        address: "20 W 46th St, New York",
        neighborhood: "Upper Midtown",
        rating: 4.7,
        reviews: 354,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 206,
        name: "Birch Coffee",
        latitude: 40.75751,
        longitude: -73.9674477,
        address: "240 E 54th St, New York",
        neighborhood: "Upper Midtown",
        rating: 4.5,
        reviews: 61,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 207,
        name: "Le Cafe Coffee",
        latitude: 40.7663395,
        longitude: -73.982921,
        address: "250 W 57th St, New York",
        neighborhood: "Upper Midtown",
        rating: 4.3,
        reviews: 322,
        features: ["coffee","wifi","food","outdoor seating"]
    },
    {
        id: 208,
        name: "Bibble & Sip",
        latitude: 40.7628359,
        longitude: -73.9851805,
        address: "253 W 51st St, New York",
        neighborhood: "Upper Midtown",
        rating: 4.5,
        reviews: 3397,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 209,
        name: "L'avion Café",
        latitude: 40.7808386,
        longitude: -73.9476236,
        address: "338 E 92nd St, New York",
        neighborhood: "Upper Midtown",
        rating: 4.6,
        reviews: 85,
        features: ["coffee","wifi","food","outdoor seating"]
    },
    {
        id: 210,
        name: "787 Coffee",
        latitude: 40.7665384,
        longitude: -73.9574235,
        address: "340 E 70th St, New York",
        neighborhood: "Upper Midtown",
        rating: 4.9,
        reviews: 1559,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 211,
        name: "Java Girl",
        latitude: 40.7641789,
        longitude: -73.9594499,
        address: "348 E 66th St, New York",
        neighborhood: "Upper Midtown",
        rating: 4.4,
        reviews: 277,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 212,
        name: "787 Coffee",
        latitude: 40.7589238,
        longitude: -73.9620028,
        address: "401 E 58th St, New York",
        neighborhood: "Upper Midtown",
        rating: 4.9,
        reviews: 1673,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 213,
        name: "Coffee Project New York | Hell's Kitchen",
        latitude: 40.7656225,
        longitude: -73.9879078,
        address: "401 W 53rd St, New York",
        neighborhood: "Upper Midtown",
        rating: 4.2,
        reviews: 204,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 214,
        name: "Sip + Co.",
        latitude: 40.7647538,
        longitude: -73.9758633,
        address: "41 W 58th St, New York",
        neighborhood: "Upper Midtown",
        rating: 4.5,
        reviews: 569,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 215,
        name: "Coffee @ 5BP",
        latitude: 40.7539883,
        longitude: -73.9854888,
        address: "5 Bryant Pk, New York",
        neighborhood: "Upper Midtown",
        rating: 4.4,
        reviews: 8,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 216,
        name: "Eat Pretty",
        latitude: 40.7738603,
        longitude: -73.9480404,
        address: "501 1/2 E 83rd St, New York",
        neighborhood: "Upper Midtown",
        rating: 4.4,
        reviews: 151,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 217,
        name: "Verve Coffee",
        latitude: 40.7618633,
        longitude: -73.9682894,
        address: "731 Lexington Ave, New York",
        neighborhood: "Upper Midtown",
        rating: 3.8,
        reviews: 37,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 218,
        name: "Ten Thousand Coffee",
        latitude: 40.7537472,
        longitude: -73.9726074,
        address: "750 3rd Ave, New York",
        neighborhood: "Upper Midtown",
        rating: 4.5,
        reviews: 247,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 219,
        name: "Blank Street Coffee",
        latitude: 40.763258,
        longitude: -73.9819312,
        address: "826 7th Ave, New York",
        neighborhood: "Upper Midtown",
        rating: 4.2,
        reviews: 129,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 220,
        name: "Blank Street Coffee",
        latitude: 40.7564053,
        longitude: -73.9707437,
        address: "830 3rd Ave, New York",
        neighborhood: "Upper Midtown",
        rating: 4.6,
        reviews: 188,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 221,
        name: "Gregorys Coffee",
        latitude: 40.757971,
        longitude: -73.9694241,
        address: "880 3rd Ave, New York",
        neighborhood: "Upper Midtown",
        rating: 4.3,
        reviews: 145,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 222,
        name: "Dan Jones Coffee Bar",
        latitude: 40.760572,
        longitude: -73.9675894,
        address: "956 3rd Ave, New York",
        neighborhood: "Upper Midtown",
        rating: 4.1,
        reviews: 133,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 223,
        name: "Blank Street Coffee",
        latitude: 40.7697763,
        longitude: -73.9624972,
        address: "985 Lexington Ave, New York",
        neighborhood: "Upper Midtown",
        rating: 4.2,
        reviews: 197,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 224,
        name: "Black Fox Coffee",
        latitude: 40.76134,
        longitude: -73.9737435,
        address: "Garden, 550 Madison Ave, New York",
        neighborhood: "Upper Midtown",
        rating: 4.5,
        reviews: 219,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 225,
        name: "Blank Street Coffee",
        latitude: 40.7823524,
        longitude: -73.957538,
        address: "1225 Madison Ave, New York",
        neighborhood: "Upper West Side",
        rating: 4.2,
        reviews: 139,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 226,
        name: "Dear Coffee",
        latitude: 40.7781245,
        longitude: -73.9567534,
        address: "1246 Lexington Ave, New York",
        neighborhood: "Upper West Side",
        rating: 4.8,
        reviews: 194,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 227,
        name: "Variety Coffee Roasters",
        latitude: 40.7788574,
        longitude: -73.9558565,
        address: "1269 Lexington Ave, New York",
        neighborhood: "Upper West Side",
        rating: 4.4,
        reviews: 562,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 228,
        name: "Blank Street Coffee",
        latitude: 40.7710073,
        longitude: -73.9599545,
        address: "1284 3rd Ave, New York",
        neighborhood: "Upper West Side",
        rating: 4.2,
        reviews: 67,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 229,
        name: "Sojourner Coffee",
        latitude: 40.8029381,
        longitude: -73.9511595,
        address: "137 W 116th St, New York",
        neighborhood: "Upper West Side",
        rating: 4.9,
        reviews: 166,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 230,
        name: "Frame NYC",
        latitude: 40.7699873,
        longitude: -73.9577292,
        address: "1413 2nd Ave, New York",
        neighborhood: "Upper West Side",
        rating: 4.7,
        reviews: 230,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 231,
        name: "Ella's Cafe Espresso & Wine Bar",
        latitude: 40.771602,
        longitude: -73.9565828,
        address: "1465 2nd Ave, New York",
        neighborhood: "Upper West Side",
        rating: 4.8,
        reviews: 370,
        features: ["coffee","wifi","food","outdoor seating"]
    },
    {
        id: 232,
        name: "Handcraft Coffee",
        latitude: 40.7736125,
        longitude: -73.959497,
        address: "151 E 77th St, New York",
        neighborhood: "Upper West Side",
        rating: 4.1,
        reviews: 283,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 233,
        name: "Park Cafe",
        latitude: 40.7995421,
        longitude: -73.96117,
        address: "153 Manhattan Ave, New York",
        neighborhood: "Upper West Side",
        rating: 4.9,
        reviews: 319,
        features: ["coffee","wifi","food","outdoor seating"]
    },
    {
        id: 234,
        name: "WFM Coffee Bar",
        latitude: 40.7796707,
        longitude: -73.9529499,
        address: "1551 3rd Ave, New York",
        neighborhood: "Upper West Side",
        rating: 4.0,
        reviews: 5,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 235,
        name: "Marathon Coffee",
        latitude: 40.7811042,
        longitude: -73.9526017,
        address: "1592 3rd Ave, New York",
        neighborhood: "Upper West Side",
        rating: 4.5,
        reviews: 76,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 236,
        name: "Joe Coffee Company",
        latitude: 40.7750164,
        longitude: -73.9802963,
        address: "187 Columbus Ave, New York",
        neighborhood: "Upper West Side",
        rating: 4.3,
        reviews: 444,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 237,
        name: "Green Lane Coffee",
        latitude: 40.794054,
        longitude: -73.971105,
        address: "204 W 96th St, New York",
        neighborhood: "Upper West Side",
        rating: 4.8,
        reviews: 56,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 238,
        name: "Zuri Coffee",
        latitude: 40.7835585,
        longitude: -73.9798741,
        address: "2218 Broadway, New York",
        neighborhood: "Upper West Side",
        rating: 4.7,
        reviews: 133,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 239,
        name: "Royal Coffee",
        latitude: 40.7855075,
        longitude: -73.9792021,
        address: "2263 Broadway, New York",
        neighborhood: "Upper West Side",
        rating: 5.0,
        reviews: 117,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 240,
        name: "787 Coffee",
        latitude: 40.7742889,
        longitude: -73.9556323,
        address: "228 E 80th St, New York",
        neighborhood: "Upper West Side",
        rating: 4.8,
        reviews: 1902,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 241,
        name: "Blank Street Coffee",
        latitude: 40.7880912,
        longitude: -73.9771422,
        address: "2345 Broadway, New York",
        neighborhood: "Upper West Side",
        rating: 4.7,
        reviews: 87,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 242,
        name: "Picky Barista",
        latitude: 40.779572,
        longitude: -73.9831361,
        address: "245 W 72nd St, New York",
        neighborhood: "Upper West Side",
        rating: 4.7,
        reviews: 305,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 243,
        name: "Blank Street Coffee",
        latitude: 40.7916831,
        longitude: -73.9742895,
        address: "2461 Broadway, New York",
        neighborhood: "Upper West Side",
        rating: 4.9,
        reviews: 398,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 244,
        name: "Fillup Coffee",
        latitude: 40.7922349,
        longitude: -73.9732406,
        address: "2486 Broadway, New York",
        neighborhood: "Upper West Side",
        rating: 4.6,
        reviews: 168,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 245,
        name: "Charlotte Cafe",
        latitude: 40.7941636,
        longitude: -73.972494,
        address: "2541 Broadway, New York",
        neighborhood: "Upper West Side",
        rating: 4.8,
        reviews: 1267,
        features: ["coffee","wifi","food","outdoor seating"]
    },
    {
        id: 246,
        name: "Plowshares Coffee Bloomingdale",
        latitude: 40.8001173,
        longitude: -73.9677814,
        address: "2730 Broadway, New York",
        neighborhood: "Upper West Side",
        rating: 4.3,
        reviews: 421,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 247,
        name: "Black Press Coffee",
        latitude: 40.7779967,
        longitude: -73.9785949,
        address: "274 Columbus Ave, New York",
        neighborhood: "Upper West Side",
        rating: 4.5,
        reviews: 415,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 248,
        name: "Frame Coffee",
        latitude: 40.7800578,
        longitude: -73.9803129,
        address: "305 Amsterdam Ave, New York",
        neighborhood: "Upper West Side",
        rating: 4.7,
        reviews: 277,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 249,
        name: "Sote Coffee Roasters",
        latitude: 40.7808931,
        longitude: -73.9797338,
        address: "329 Amsterdam Ave, Manhattan",
        neighborhood: "Upper West Side",
        rating: 4.9,
        reviews: 212,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 250,
        name: "Cositas Café",
        latitude: 40.7720664,
        longitude: -73.9536127,
        address: "353 E 78th St, New York",
        neighborhood: "Upper West Side",
        rating: 4.9,
        reviews: 149,
        features: ["coffee","wifi","food","outdoor seating"]
    },
    {
        id: 251,
        name: "Bluestone Lane Upper West Side Café",
        latitude: 40.7836728,
        longitude: -73.9777158,
        address: "417 Amsterdam Ave, New York",
        neighborhood: "Upper West Side",
        rating: 4.4,
        reviews: 673,
        features: ["coffee","wifi","food","outdoor seating"]
    },
    {
        id: 252,
        name: "Oslo Coffee Roasters",
        latitude: 40.7691558,
        longitude: -73.953699,
        address: "422 E 75th St, New York",
        neighborhood: "Upper West Side",
        rating: 4.6,
        reviews: 371,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 253,
        name: "About Coffee",
        latitude: 40.7833765,
        longitude: -73.9742304,
        address: "445 Columbus Ave, New York",
        neighborhood: "Upper West Side",
        rating: 4.2,
        reviews: 306,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 254,
        name: "ARTISAN CAFE",
        latitude: 40.7899805,
        longitude: -73.9735738,
        address: "608a Amsterdam Ave, New York",
        neighborhood: "Upper West Side",
        rating: 4.8,
        reviews: 153,
        features: ["coffee","wifi","food","outdoor seating"]
    },
    {
        id: 255,
        name: "Sensuous Bean of Columbus Ave",
        latitude: 40.7758672,
        longitude: -73.9795241,
        address: "66 W 70th St, New York",
        neighborhood: "Upper West Side",
        rating: 4.4,
        reviews: 122,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 256,
        name: "Picky Barista",
        latitude: 40.790596,
        longitude: -73.9688962,
        address: "667 Columbus Ave, New York",
        neighborhood: "Upper West Side",
        rating: 4.5,
        reviews: 486,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 257,
        name: "White Noise Coffee - Coffee Shop & Roastery",
        latitude: 40.7701469,
        longitude: -73.9919315,
        address: "829 11th Ave, Manhattan",
        neighborhood: "Upper West Side",
        rating: 4.7,
        reviews: 279,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 258,
        name: "Ralph's Coffee",
        latitude: 40.7716586,
        longitude: -73.9657658,
        address: "888 Madison Ave, New York",
        neighborhood: "Upper West Side",
        rating: 4.3,
        reviews: 1141,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 259,
        name: "Caffe Aronne",
        latitude: 40.7700442,
        longitude: -73.9627338,
        address: "976A Lexington Ave, New York",
        neighborhood: "Upper West Side",
        rating: 4.6,
        reviews: 796,
        features: ["coffee","wifi","food","outdoor seating"]
    },
    {
        id: 260,
        name: "Paper Sons Cafe",
        latitude: 40.7140524,
        longitude: -73.9985851,
        address: "10 Mott St, New York",
        neighborhood: "Unknown Neighborhood",
        rating: 4.7,
        reviews: 87,
        features: ["coffee","wifi","food","outdoor seating"]
    },
    {
        id: 261,
        name: "Embriago Coffee",
        latitude: 40.7212926,
        longitude: -73.9929505,
        address: "5 Rivington St, New York",
        neighborhood: "Unknown Neighborhood",
        rating: 5.0,
        reviews: 53,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 262,
        name: "The Green Room by Blank Street Coffee",
        latitude: 40.7224442,
        longitude: -73.9972503,
        address: "63 Spring St, New York",
        neighborhood: "Unknown Neighborhood",
        rating: 4.8,
        reviews: 289,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 263,
        name: "MCM coffee",
        latitude: 40.7091894,
        longitude: -74.0058987,
        address: "88 Fulton St Space E, New York",
        neighborhood: "Unknown Neighborhood",
        rating: 4.8,
        reviews: 204,
        features: ["coffee","wifi","outdoor seating"]
    },
    {
        id: 264,
        name: "drip coffee makers",
        latitude: 40.6976939,
        longitude: -73.9930618,
        address: "Inside Clark Street Station, 100 Henry St, Brooklyn",
        neighborhood: "Unknown Neighborhood",
        rating: 4.9,
        reviews: 149,
        features: ["coffee","wifi","outdoor seating"]
    }
];

export { coffeeShops };